// View-mode worldwide search.
//
// The index is a static JSON file generated by scripts/extract-search-index.py
// (rows: [name, kind, osm_type, osm_id, lon, lat, grade?]). It is fetched
// lazily on the first interaction with the search box, so people who only
// browse never download it.
import type { Map as LibreMap } from 'maplibre-gl'
import { gradeColorForTag } from './grades'
import { loadSearchIndex, normalize, type OsmType, type PlaceEntry, type PlaceKind } from './searchIndex'
import { showRoute, showBoulder } from './sidebar'

const OSM_TYPE: Record<OsmType, string> = { n: 'node', w: 'way', r: 'relation' }
const KIND_LABEL: Record<PlaceKind, string> = { p: 'Problem', s: 'Sector', a: 'Area' }
const KIND_ZOOM: Record<PlaceKind, number> = { p: 19, s: 14, a: 11 }
const MIN_QUERY = 2
const MAX_RESULTS = 20
const DEBOUNCE_MS = 120

/** Rank exact matches, then prefixes, word starts and finally substrings. */
function search(entries: PlaceEntry[], query: string): PlaceEntry[] {
  const q = normalize(query.trim())
  if (q.length < MIN_QUERY) return []
  const matches: Array<{ entry: PlaceEntry; score: number }> = []
  for (const entry of entries) {
    const at = entry.norm.indexOf(q)
    if (at === -1) continue
    let score = 3
    if (at === 0) score = entry.norm.length === q.length ? 0 : 1
    else if (entry.norm[at - 1] === ' ' || entry.norm[at - 1] === '-' || entry.norm[at - 1] === "'") score = 2
    matches.push({ entry, score })
  }
  matches.sort((a, b) =>
    a.score - b.score ||
    a.entry.norm.length - b.entry.norm.length ||
    a.entry.name.localeCompare(b.entry.name)
  )
  return matches.slice(0, MAX_RESULTS).map(match => match.entry)
}

export function initSearch(map: LibreMap): void {
  const container = document.createElement('div')
  container.className = 'search'

  const input = document.createElement('input')
  input.type = 'search'
  input.className = 'search-input'
  input.placeholder = 'Search problems, sectors, areas'
  input.setAttribute('aria-label', input.placeholder)
  input.autocomplete = 'off'
  input.spellcheck = false

  const results = document.createElement('ul')
  results.className = 'search-results'
  results.setAttribute('role', 'listbox')
  results.hidden = true

  container.append(input, results)
  document.getElementById('app')!.append(container)

  let items: PlaceEntry[] = []
  let index: PlaceEntry[] | undefined
  let active = -1
  let timer: number | undefined
  let status: 'idle' | 'loading' | 'failed' = 'idle'
  let requested = ''

  const close = () => {
    results.hidden = true
    results.replaceChildren()
    items = []
    active = -1
  }

  const renderStatus = (text: string) => {
    const item = document.createElement('li')
    item.className = 'search-status'
    item.textContent = text
    results.replaceChildren(item)
    results.hidden = false
  }

  const render = () => {
    if (status === 'loading') return renderStatus('Loading search index…')
    if (status === 'failed') return renderStatus('Search is unavailable right now. Try again later.')
    if (requested.length < MIN_QUERY) return close()

    items = search(index ?? [], requested)
    if (!items.length) return renderStatus('No matches.')

    const fragment = document.createDocumentFragment()
    items.forEach((entry, index) => {
      const item = document.createElement('li')
      item.setAttribute('role', 'option')
      const button = document.createElement('button')
      button.type = 'button'
      button.className = 'search-result'
      button.setAttribute('aria-selected', String(index === active))
      button.addEventListener('mousedown', event => event.preventDefault()) // Keep input focus.
      button.addEventListener('click', () => open(entry))

      const kind = document.createElement('span')
      kind.className = `search-result-kind kind-${entry.kind}`
      kind.textContent = KIND_LABEL[entry.kind]

      const body = document.createElement('span')
      body.className = 'search-result-body'

      const name = document.createElement('span')
      name.className = 'search-result-name'
      name.textContent = entry.name
      body.append(name)

      const context: string[] = []
      if (entry.sector) context.push(`Sector: ${entry.sector}`)
      if (entry.area) context.push(`Area: ${entry.area}`)
      if (context.length) {
        const meta = document.createElement('span')
        meta.className = 'search-result-meta'
        meta.textContent = context.join(' · ')
        body.append(meta)
      }

      button.append(kind, body)
      const grades: Array<[string, string]> = []
      if (entry.font) grades.push(['climbing:grade:font', entry.font])
      if (entry.hueco) grades.push(['climbing:grade:hueco', entry.hueco])
      if (grades.length) {
        const wrap = document.createElement('span')
        wrap.className = 'search-result-grades'
        for (const [tagKey, value] of grades) {
          const grade = document.createElement('span')
          grade.className = 'search-result-grade'
          grade.textContent = value
          grade.style.color = gradeColorForTag(tagKey, value)
          wrap.append(grade)
        }
        button.append(wrap)
      }
      item.append(button)
      fragment.append(item)
    })
    results.replaceChildren(fragment)
    results.hidden = false
  }

  const open = (entry: PlaceEntry) => {
    close()
    if (entry.kind === 'p') {
      showRoute({
        name: entry.name,
        osm_type: OSM_TYPE[entry.osm],
        osm_id: entry.id,
        ...(entry.font ? { 'climbing:grade:font': entry.font } : {}),
        ...(entry.hueco ? { 'climbing:grade:hueco': entry.hueco } : {})
      }, entry.lon, entry.lat)
    } else {
      showBoulder({
        name: entry.name,
        kind: entry.kind === 's' ? 'sector' : 'area',
        osm_type: OSM_TYPE[entry.osm],
        osm_id: entry.id
      }, entry.lon, entry.lat)
    }
    map.flyTo({ center: [entry.lon, entry.lat], zoom: KIND_ZOOM[entry.kind], essential: true })
  }

  const ensureIndex = () => {
    if (index || status === 'loading') return
    status = 'loading'
    if (requested.length >= MIN_QUERY) render()
    void loadSearchIndex()
      .then(list => { index = list; status = 'idle'; render() })
      .catch(() => { status = 'failed'; render() })
  }

  const move = (delta: number) => {
    if (!items.length) return
    active = (active + delta + items.length) % items.length
    render()
    results.querySelectorAll('.search-result')[active]?.scrollIntoView({ block: 'nearest' })
  }

  input.addEventListener('focus', () => ensureIndex())

  input.addEventListener('input', () => {
    requested = input.value
    active = -1
    window.clearTimeout(timer)
    if (requested.trim().length < MIN_QUERY) {
      close()
      return
    }
    if (!index) {
      ensureIndex()
      return
    }
    timer = window.setTimeout(render, DEBOUNCE_MS)
  })

  input.addEventListener('keydown', event => {
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp') {
      event.preventDefault()
      if (results.hidden && items.length) render()
      move(event.key === 'ArrowDown' ? 1 : -1)
    } else if (event.key === 'Enter') {
      if (active >= 0 && items[active]) {
        event.preventDefault()
        open(items[active])
      }
    } else if (event.key === 'Escape') {
      close()
      input.blur()
    }
  })

  // Close when focus moves elsewhere (clicking the map, sidebar, etc.).
  document.addEventListener('pointerdown', event => {
    if (!container.contains(event.target as Node)) close()
  })
}
